
print (node.heap())
PIN = 4
print (node.heap())
local dht22 = require("dht22")
print (node.heap())
dht22.read(PIN)
print (node.heap())
Temperature = dht22.getTemperatureString()
print (node.heap())
Humidity = dht22.getHumidityString()
print (node.heap())
Light = adc.read(0)
print (node.heap())
print ("Temperature: "..Temperature)
print (node.heap())
print ("Humidity: "..Humidity)
print (node.heap())
print ("Light: "..Light)
print (node.heap())
dht22 = nil
print (node.heap())
